FROM node:20-alpine

WORKDIR /app

# Copy package file
COPY package.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose BASE port
EXPOSE 5174

# Start development server
CMD ["npm", "run", "start:dev"]
