#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export PATH="/usr/local/bin:$PATH"

# Run checks in api directory
cd api

# Run lint-staged on staged files
npx lint-staged

# Type check
npm run typecheck
